# Generated by Django 5.2 on 2025-04-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('bar', 'Bar'), ('restaurant', 'Restaurante'), ('museum', 'Museo'), ('park', 'Parque'), ('shopping_center', 'Centro Comercial'), ('kids_zone', 'Zona de Juegos para Niños'), ('cinema', 'Cine'), ('beach', 'Playa'), ('mountain', 'Montaña'), ('city', 'Ciudad'), ('nature', 'Naturaleza'), ('hotel', 'Hotel'), ('other', 'Otro')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
